# GLOBAL SITE SETTINGS

# General
seo_title: ""
title: "Big Red Sky"
company: "Thomson Reuters"
description: ""

# Contact Info
email: helpdesk@bigredsky.com
phone: 1300 733 056
fax: (05) 555 555
address: "ABC Street, Earth"

# Social Networks
facebook: ""

# Links
feedback: "https://www.nicereply.com/thomson-reuters-anz.bigredsky/bigredsky"
help: "http://www.bigredsky.com/index.php?page=training"
privacy_policy: "http://www.thomsonreuters.com.au/terms/privacy-policy.aspx"
terms_of_use: "http://www.thomsonreuters.com.au/terms/online-terms-of-use.aspx"

# Site Links
thomson_reuters_au: "http://www.thomsonreuters.com.au"

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"